package wtone

import (
	"bytes"
	"fmt"
	"os"

	"github.com/BurntSushi/toml"
	"github.com/leraniode/wondertone/palette"
)

// SaveWTone writes a Palette to a .wtone file.
// Creates or overwrites the file at path.
func SaveWTone(path string, p *palette.Palette) error {
	data, err := MarshalWTone(p)
	if err != nil {
		return err
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("wtone: cannot write %q: %w", path, err)
	}
	return nil
}

// MarshalWTone serialises a Palette to .wtone format bytes.
// Useful when you want the content without writing to disk.
func MarshalWTone(p *palette.Palette) ([]byte, error) {
	r := raw{
		Name:        p.Name(),
		Description: p.Description(),
		Mood:        p.Mood(),
		Author:      p.Author(),
		Version:     p.Version(),
	}
	if r.Version == "" {
		r.Version = "1.0.0"
	}

	for _, t := range p.All() {
		l, c, h := t.OKLCH()
		rc := rawColor{
			Name:   t.Name(),
			L:      roundF(l, 6),
			C:      roundF(c, 6),
			H:      roundF(h, 4),
			Energy: roundF(t.Energy(), 4),
			Mood:   t.Mood(),
		}
		if t.AlphaValue() < 1.0 {
			rc.Alpha = roundF(t.AlphaValue(), 4)
		}
		// Don't store mood if it matches the palette mood (inherited)
		if rc.Mood == p.Mood() {
			rc.Mood = ""
		}
		r.Colors = append(r.Colors, rc)
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by wondertone — https://github.com/leraniode/wondertone\n\n")

	enc := toml.NewEncoder(&buf)
	if err := enc.Encode(r); err != nil {
		return nil, fmt.Errorf("wtone: encode error: %w", err)
	}
	return buf.Bytes(), nil
}

// roundF rounds a float64 to n decimal places.
func roundF(v float64, decimals int) float64 {
	factor := 1.0
	for i := 0; i < decimals; i++ {
		factor *= 10
	}
	return float64(int(v*factor+0.5)) / factor
}
